In [4]:
from sqlalchemy import create_engine, inspect
import pandas as pd

In [9]:
engine = create_engine('sqlite:///DisasterResponse.db')
inspector = inspect(engine)

print(inspector.get_table_names())

for table_name in inspector.get_table_names():
    for column in inspector.get_columns(table_name):
        print("Column: %s" % column['name'])

['labeled_messages']
Column: id
Column: message
Column: original
Column: genre
Column: related
Column: request
Column: offer
Column: aid_related
Column: medical_help
Column: medical_products
Column: search_and_rescue
Column: security
Column: military
Column: child_alone
Column: water
Column: food
Column: shelter
Column: clothing
Column: money
Column: missing_people
Column: refugees
Column: death
Column: other_aid
Column: infrastructure_related
Column: transport
Column: buildings
Column: electricity
Column: tools
Column: hospitals
Column: shops
Column: aid_centers
Column: other_infrastructure
Column: weather_related
Column: floods
Column: storm
Column: fire
Column: earthquake
Column: cold
Column: other_weather
Column: direct_report

In [17]:
engine = create_engine('sqlite:///DisasterResponse.db')
df=pd.read_sql_table('labeled_messages', engine)
df.iloc[:,4:]

,related,request,offer,aid_related,medical_help,medical_products,search_and_rescue,security,military,child_alone,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,1,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26172,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26173,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26174,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26175,1,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
26176,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0